// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ES5IEOvWQpL_YUM6H3RKMTStckfOUWs',
    appId: '1:1031215377841:web:ca1221b8929048f369e190',
    messagingSenderId: '1031215377841',
    projectId: 'flutter-chat-app-83cc2',
    authDomain: 'flutter-chat-app-83cc2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-83cc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeFvEo5uH3TX8dpPJLxdFoLM5vyvIyQME',
    appId: '1:1031215377841:android:f914b1361f2a846a69e190',
    messagingSenderId: '1031215377841',
    projectId: 'flutter-chat-app-83cc2',
    storageBucket: 'flutter-chat-app-83cc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeLeDsAxPAwnwBOiIKDxXcvnUtF_Nsz8E',
    appId: '1:1031215377841:ios:1f6ee237cde94dc469e190',
    messagingSenderId: '1031215377841',
    projectId: 'flutter-chat-app-83cc2',
    storageBucket: 'flutter-chat-app-83cc2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeLeDsAxPAwnwBOiIKDxXcvnUtF_Nsz8E',
    appId: '1:1031215377841:ios:75a441b1d95e448369e190',
    messagingSenderId: '1031215377841',
    projectId: 'flutter-chat-app-83cc2',
    storageBucket: 'flutter-chat-app-83cc2.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
